language: node_js
node_js:
- 4.2.6
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_bba79517ddc5_key -iv $encrypted_bba79517ddc5_iv
  -in travis_rsa.enc -out .travis/travis_rsa -d
script:
- echo Deploying!
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis_rsa
- ssh-add .travis/travis_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: bRxB3fsEvfgnPLHGN8qLA63mWOWJQt4sPdC3sfeEQV+KDwDL5UqiL6Ck8EXxwW44xCGGQpSlSfmmKVpktenKpNzuB9pF5+mn6bzFHYyaDWgw/MURblZvMTulcuPQM4sHLVoVU+6Z/oQz7BvGuiSvBCfJG5gAMrq0wgNAuNANB6+AFKCDSCWk806mYIQzSWWGr8AIDEedHQ2YfFO+AGvzTPK/1W9d7rOGQciuc4fu/NutMXXMUk4KWe5tniDDBB4zzF91ulQieJrmMXJcN1PAgV0XznAPAqqcO9chGhDBp5rPLbnMgAqksqeGOoeu4mFxZt34frq24GMffgyojMeK0HL3j9R4WqYVUt7vtWDlAFgSFpAnOIsUT5YRMiROf+fa6/1OlGZZ/jW/maZ8r6YYuIkKGaCOjz7HFjWYT0L+1UpQ2QWp1im+EPheFUFJ71s0npZoe6scvJEVLMdNxjQDSDmqpaUoSrYgcpsldTb8p8JhsV2D8c9gy8kv3KHYYf+HfapoA+qQjxa3ZikAxg7A3XHeZAXA4Ykuuhf7crFMN2BcIEhKS9DyOLgbeFpQwaywUABqIjDL+Dt8B4nuN7nX36HHsH3RGxD34BcyTmDWFYrlmWG0TWcmMVqWD8eiEAxNR+1Jvf1p3wR3w3G6wlM2pREOMs96UQH1NfpsJ0fo7BU=
  - secure: K0dfSvhEwbMjZYJa2ChuUCxFjQ9NdF0KurexMauSv1lFswSpgXGZMosIJNq+sC6vsYaoQ72ae0iKdFigtUnw/G6/GVh6ysZen8tW1VDyflJ+3ju6GZ0UrzAFu3lXKayRL/tYiShLWKdaYFrx3bYXhVQC9IVViSnwjz3HxeyBANyKjwNQ/2QVEdTpmgE+0ZnIh+VS8Gh9MvppHOGKoLBpXZooDf8NZr/l2C2itBgchX19VCQBU0Y9v37qxUPTTSw02tRo/GZkcxWpAGhk0lgJfzpqppb7QpIIG4sskgsr19q5129Qq8CyBsJeaOEXmkMKx4BxkmUEs6eG8/wWPXgOpQl198CeBkD4BNEU6P4ssn0qICEa0HZJXbBN5WaenEGfnw0PrwOIB1pzBaqyK4aPdaeFQtcw7O2a5CKOC675BpjVsoZMRMjilUz1U3VjWUfOvnYyVT14P3UhmJHwdab3buKiuuRfeyk+KvzsKVWeH4RiaFSjAykPvoitiNYNtacMwPlNTf/DPz1NAwU3O84eoufHrVwc0bUGke7run5dnY+h0pp0mfIqJbsBh4MErXLehnBPE2tqPBB8NR9xerl4wzx5w9FM4EQgEtWuy2JrBI+WYf6cqcztaW8tzzQBSQE/NT9uW+xj7D/4kvK9Q911eLqxpByzpWZ257IrEvvuJa8=
